#!/usr/bin/env bash
set -euo pipefail

# load env variables
if [[ -f ".env.local" ]]; then
  echo "Loading environment from .env.local"
  set -a
  source .env.local
  set +a
fi

# Detect branch (works locally + in CI)
BRANCH="${1:-$(git rev-parse --abbrev-ref HEAD)}"

export BRANCH

python tools/publish_confluence.py
